insert into product (title, description, miniature, category, price, type, author) values ('Monstera Reliciosa', 'Monstera deliciosa to okazałe, modne, silnie płożące się pnącze o bardzo okazałych, spektakularnych liściach.', 'https://i.ibb.co/4P2TYGc/monstera-deliciosa.jpg', 'Plant Monsteria', 200, 'PLANTS', 'Admin');
insert into product (title, description, miniature, category, price, type, author) values ('Small Terrarium with Fikus', 'Small Terrarium with Fikus in a bottle', 'https://previews.dropbox.com/p/thumb/ABnODu7Xq3_v_Lyub0ED2LuJRrwkfkOkGaT4IE4iRJOJ82iCAwSwod3CzvsbWIpoy9LA8GsT8fsFkHZ5rjRjiLu6512bqPODIM7Mr9Km7QqyyKhqoXFFqf7k2Cp6aSmgZZddXc9FO_ZHwQhdsb1gPV_l3sGiEQZg9vXDiDZGZLy8YURBLUa8QZB-mggvl_Zc9fB5ks4jUFYMEwKfOJicBzwb-gCY1dkshI1Tjqhz7RkkKQ5Fio_-_aBVby0S6TXyHUS81vDQxiRoTW1gu8pkHqexB6Y18iM3xt7QduP6qHz1b_fSL2A-J84XBGQePy2K9dkvRTP6QZFsN7OLV3MX8tnbRyXOsyVnn2a8ZtACafkaQNgqyh4XSgbOwpU3x4Bqf74/p.jpeg', 'Terrarium Plant', 300, 'TERRARIUM', 'Admin');
insert into product (title, description, miniature, category, price, type, author) values ('Terrarium with succulent', 'Small plants in a bottle', 'https://previews.dropbox.com/p/thumb/ABnm_G7CfCD06Ay9BzottjNKJqEOnbQ2J-arJWc53_1R-d1hTyeXMxM_GUh-iFYE96-kbjBL1h0iOIgSMP3skOw4UD8spRpgK8aK7OMVFcgZAwbFT7uNJxp1oZ0kWcL2n02-kC0LDvv8f-vx4DtnZh8FVvr7AlpxhLeqUXcV97Kwsph8DhuAbbWjq0rSDUFkwUicHC7j71_K5OkZ7-vfHQWCwf5rhWRXs0_ZexAxev8k7FrIXps50C99VbVRgig7_OUeIp-R9KgDdasXyvWpQ0yH0hHimduxR1xeJM3GLyj9msZPX8jXhDymnE-ckTf_qK40P48x7iyPOAY5rZy8xDIwzYRJXtZ_6mduqhTLlF-gHSh7xbi5_thB9azlJ-kRR2c/p.jpeg', 'Terrarium Plant', 400, 'TERRARIUM', 'Admin');
insert into product (title, description, miniature, category, price, type, author) values ('Terrarium in bottle', 'Small garden terrarium', 'https://previews.dropbox.com/p/thumb/ABltcr4k53scy9vm1aQcatdMW-j1ucaJ38LYBWnD0Cm7JVRwfT2vNZeRgVVVcR0YYdhgpGUqAsSgLPzFyPOW9AKQ9O1Q-VY3N0prfnID5rtbRr3uf87da63FTd8T3f6dKsjY2556qR5WRZfNFu_OMvmRcsuqk_1_JUxFkG5_P0bFyupprAHDUZcq-NO_jD35Po1pJfz0OrDO787Ty6tdFUTnoa1yHgXl0CCtXYBOOaHUKAGIHiYlKcEuyow-lNM9wzKcWFdTK0LqVvFSTRNyShB7kcI5gCd1cRJzuk80dwl0mEePbRxJaIKl7XaWIMsPQRZzlQJyrPDHsWYWDM9XogItOKsKOk-l-HdstNqHBLbejeJOEHYgxopzdxk0ATiWra8/p.jpeg', 'Terrarium Plant', 500, 'TERRARIUM', 'User');
insert into product (title, description, miniature, category, price, type, author) values ('Fikus and Stone', 'A garden terrarium', 'https://previews.dropbox.com/p/thumb/ABleI_zzscxOOPCwk3ApJe9lH5bg3jWbPQDq09qPjWX50mJ4l4eIQJQOBKFEsiWYgjUNeTZz6mS1XDBegIbfQGXY1DHy9ftQZ6EI__lW_9zLCILP0YzfBKygmZCt4QJXrP-MuqaCRxOsVOOrWQ3tleotJw6Iovqq7MMfEGU6eHS0KE9QPpcbo8IeT-Mf-PG9TCysvGuMwwzjhWpfa49hFXA5JGsBb-ut5JjT5O0NXiDKHYqWjToNZIKCdxXXjoHVIK4M9IE6mmLbXsTITS1DVwkkRXMQV7S3WtAxL9pqI4qkoTL4cxkXfE1NPOuyUB9sNqyHJhh0OwzMyMUEWkXnBKIdcujzyC2mu83nLRY5p9vls3II5OwLNDIXflc92zPPUmE/p.jpeg', 'Terrarium Plant', 600, 'TERRARIUM', 'User');
insert into product (title, description, miniature, category, price, type, author) values ('Monstera Monkey', 'Monstera Monkey or also known as Monstera deliciosa is native to the tropical forests of Central America. Its particular leaves that imitate the holes in Swiss cheese make it a very unique and striking plant', 'https://previews.dropbox.com/p/thumb/ABmHVPKsqXMjPUV_Pfy6IuVYt5T44bgqMfNQaB5w4GRK7xiEktc7I8oe_bysjoiNDVdmDJGm6U2yeeCyqgwQ-l6GizXhyjcf6KF42WqnsqiFYPYXTTo57nTaTmtIBQRY1JhY6dSGl26GcgU_jth2yvu37QpuRheJkGZIV5kBmZs-gZuSGRIaUr5RhqKkTonSfqVAeIYm5jB7uu_et0GteXv1TP5iIurdpivkiu9yX6d9EmyG6KpiEZPbcxwJk1j853a5CNb5HlTt9nmtUZG8ca8GPhUkOR2Hc3gXpMKsLu1rpaMkZVQtGNChUQTjx8pN4E3ep_ZHVGOuLKENarL7lIqJZ7P-bE7uUKj7wSgHOGPS74VicKpxU1LujHecVLR5nEI/p.jpeg', 'Plant Monsteria', 300, 'PLANTS', 'Admin');
insert into product (title, description, miniature, category, price, type, author) values ('Monstera Deliciosa', 'Adminstera deliciosa is mainly cultivated for its large, glossy, dark green leaves that can reach up to one metre in length', 'https://previews.dropbox.com/p/thumb/ABmiiLS-9D5xndjviUvQcZQYgerIYzzdimtxMjFGPB2hR8oARtKFNDBC39fqk2E0c3PwzT2OcTuJHsrvrhWfbqPWPpM2bMm_0xwAdBzb3QHd8zFnWFCHlPyKFs4dmTdF3Gkw431kh2NXNhgbySehV3FPxSrjYKn4RCcm1mw1QPa_GgQAmGTYfnKYASjv4wndC3HZzVCX304fpxaAoVhNZrdYm1VkX6I3hVIK0tckGvVcyiEYAPmP_Xw3WgnuqCzDerl_HoPNiwc3B03R_LAKnr5q3h6MgsEqDSvcTWs0vo2X-P9KiD_wHQbrzWZY2y1gc50Rop4LBvgxBvVnxQSb4VM1CHy4sNaCHD09UmWry-x-3KVw8HAWPro1T1-XEaGK_AM/p.jpeg', 'Plant Monsteria', 200, 'PLANTS', 'Admin');
insert into product (title, description, miniature, category, price, type, author) values ('Monstera Variegata', 'A variety with variegated leaves is Monstera Variegata. It grows relatively slowly, is a bit more sensitive and requires much more heat', 'https://previews.dropbox.com/p/thumb/ABlC39sz1-V8XOjnCiPisKWJ7V9I99Pp-FlJpn1SrJSICK3jz2IJjif-v9RuvMtWx5A8pZ9SVVfoCNbzKJydfTfZ_wFCWXZy6ocPQGq1mRuzS1oigQusSmat1cwH19kRdYNTWBValv8JPkF0G--nz8ZqcAQC-mhrxFGd-dJEhH_L7QqeEJlOojfc3mf9jblmlwuuPK0AqILcQMaRvxx25f1YbbRKBUP9Yb7zy7JEvAmKl1XncPM9Xfo4QQuQ0o-Zhr9tLA43t-DnOfv-aA0tLjblTif0k7VI97B6oyq4NmG5gJyRoMm28sr-Rxy08F64A9JBLHuyAezvx_0QYhh-8TVCraOSSV2IqW9Eota9uBZj-HXM03juAfe8UlThJS4PzT8/p.jpeg', 'Plant Monsteria', 600, 'PLANTS', 'Admin');

insert into role (id, name) values(1, 'ADMIN');
insert into role (id, name) values(2, 'USER');

insert into user_table (id, username, password) values(1, 'admin', '$2a$12$c3ZaizMLwEc40BS/uqEYjuCBKXIrCrzDxW3i6Js8PGgTrZjH9RAg2');
insert into user_table (id, username, password) values(2, 'user', '$2a$12$96BUERE6i.WgeotUYMEWBOnrgptdGmV1HahwOFWqrJKjEOzEP5xBG');

insert into user_role (user_id, role_id) values(1,1);
insert into user_role (user_id, role_id) values(1,2);
insert into user_role (user_id, role_id) values(2,2);